const { Schema, model } = require("mongoose");

const bookingSchema = new Schema(
  {
    bookingNumber: { type: String, required: true, unique: true },
    awbNumber: { type: String, required: true, unique: true },
    enquiryNumber: { type: String, unique: true },
    preBookingNumber: { type: String, unique: true },
    customerEmail: { type: String, required: true },
    customerMobile: { type: String, required: true },
    origin: { type: String, required: true },
    destination: { type: String, required: true },
    mode: { type: String, required: true },
    pickupRequired: { type: String, required: true },
    deliveryRequired: { type: String, required: true },
    segment: { type: Schema.Types.ObjectId, ref: "Segment" },
    shipmentTerm: { type: String, required: true },
    shipmentDate: { type: Date, required: true },
    freight: { type: String, required: true },
    shipperAddress: { type: String, required: true },
    shipperCity: { type: String, required: true },
    shipperState: { type: String, required: true },
    shipperCountry: { type: String, required: true },
    shipperPoBoxNo: { type: String, required: true },
    shipperMobileNumber: { type: String, required: true },
    shipperPhoneNumber: { type: String, required: true },
    shipperEmail: { type: String, required: true },
    consigneeAddress: { type: String, required: true },
    consigneeCity: { type: String, required: true },
    consigneeState: { type: String, required: true },
    consigneeCountry: { type: String, required: true },
    consigneePoBoxNo: { type: String, required: true },
    consigneeMobileNumber: { type: String, required: true },
    consigneePhoneNumber: { type: String, required: true },
    consigneeEmail: { type: String, required: true },
    billingCustomerAddress: { type: String, required: true },
    billingCustomerCity: { type: String, required: true },
    billingCustomerState: { type: String, required: true },
    billingCustomerCountry: { type: String, required: true },
    billingCustomerPoBoxNo: { type: String, required: true },
    billingCustomerMobileNumber: { type: String, required: true },
    billingCustomerPhoneNumber: { type: String, required: true },
    billingCustomerEmail: { type: String, required: true },
    hazardous: { type: String },
    stackAble: { type: String },
    cargoDescription: { type: String, required: true },
    commodityDescription: { type: String, required: true },
    billingCustomerName: { type: String, required: true },

    shipperName: {
      type: Schema.Types.ObjectId,
      ref: "Customer",
      required: true,
    },
    consigneeName: {
      type: Schema.Types.ObjectId,
      ref: "Customer",
      required: true,
    },
    customerName: {
      type: Schema.Types.ObjectId,
      ref: "Customer",
      required: true,
    },
    status: { type: String },
    dimensionDetail: { type: Array },
    siteId: { type: Schema.Types.ObjectId, ref: "Site", index: true },
    userId: { type: Schema.Types.ObjectId, ref: "User", index: true },
    created_at: { type: Date, required: true },
    updated_at: { type: Date, required: true },
  },
  { index: { siteId: 1, userId: 1 } }
);

const Booking = model("Booking", bookingSchema);
module.exports = Booking;
